stepback: true
command_type: test
ignore:
  - "*.md"
  - ".github/*"

modules:
- name: evergreen
  repo: git@github.com:evergreen-ci/evergreen.git
  branch: main

#######################################
#              Functions              #
#######################################
functions:
  get-project:
    command: git.get_project
    type: setup
    params:
      directory: spruce

  get-evergreen-project:
    command: git.get_project
    type: setup
    params:
      directory: spruce
      revisions:
        evergreen: ${evergreen_rev}

  setup-mongodb:
    - command: subprocess.exec
      type: setup
      params:
        env:
          gobin: /opt/golang/go1.16/bin/go
          MONGODB_URL: ${mongodb_url}
          DECOMPRESS: ${decompress}
        working_dir: spruce/evergreen
        command: make get-mongodb
    - command: subprocess.exec
      type: setup
      params:
        background: true
        working_dir: spruce/evergreen
        command: make start-mongod
    - command: subprocess.exec
      type: setup
      params:
        working_dir: spruce/evergreen
        command: make configure-mongod

  run-make:
    command: subprocess.exec
    params:
      working_dir: spruce/evergreen
      binary: make
      args: ["${make_args|}", "${target}"]
      background: false
      env:
        GOROOT: /opt/golang/go1.16

  run-make-background:
    command: subprocess.exec
    params:
      working_dir: spruce/evergreen
      binary: make
      args: ["${make_args|}", "${target}"]
      background: true
      env:
        SETTINGS_OVERRIDE: file
        GOROOT: /opt/golang/go1.16

  sym-link:
    command: shell.exec
    params:
      working_dir: spruce
      script: |
        ln -s evergreen/graphql/schema.graphql sdlschema.graphql

  yarn-start:
    command: shell.exec
    type: setup
    params:
      working_dir: spruce
      background: true
      script: |
        export PATH=/opt/nodejs/node-v16.13.0-linux-x64/bin:$PATH
        yarn run dev

  
  yarn-install:
    command: shell.exec
    params:
      working_dir: spruce
      script: |
        export PATH=/opt/nodejs/node-v16.13.0-linux-x64/bin:$PATH
        yarn

  yarn-test:
    command: shell.exec
    params:
      working_dir: spruce
      script: |
        export PATH=/opt/nodejs/node-v16.13.0-linux-x64/bin:$PATH
        yarn test --reporters=default --reporters=jest-junit --testPathIgnorePatterns=storybook.test.ts

  yarn-eslint:
    command: shell.exec
    params:
      working_dir: spruce
      script: |
        export PATH=/opt/nodejs/node-v16.13.0-linux-x64/bin:$PATH
        yarn eslint:strict

  yarn-tsc:
    command: shell.exec
    params:
      working_dir: spruce
      script: |
        export PATH=/opt/nodejs/node-v16.13.0-linux-x64/bin:$PATH
        yarn check-types

  yarn-build:
    command: shell.exec
    params:
      working_dir: spruce
      script: |
        export PATH=/opt/nodejs/node-v16.13.0-linux-x64/bin:$PATH
        yarn build

  yarn-build-storybook:
    command: shell.exec
    params:
      working_dir: spruce
      script: |
        export PATH=/opt/nodejs/node-v16.13.0-linux-x64/bin:$PATH
        yarn build-storybook
    
  yarn-snapshot:
    command: shell.exec
    params:
      working_dir: spruce
      script: |
        export PATH=/opt/nodejs/node-v16.13.0-linux-x64/bin:$PATH
        yarn test --reporters="jest-junit" --reporters="default" --testPathPattern="storybook.test.ts"

  yarn-analyze:
    command: shell.exec
    params:
      working_dir: spruce
      script: |
        export PATH=/opt/nodejs/node-v16.13.0-linux-x64/bin:$PATH
        yarn analyze

  check-codegen:
    command: shell.exec
    params:
      working_dir: spruce
      shell: bash
      script: |
        export PATH=/opt/nodejs/node-v16.13.0-linux-x64/bin:$PATH
        chmod +x check_codegen.sh
        ./check_codegen.sh

  run-cypress-tests:
    command: shell.exec
    params:
      working_dir: spruce
      script: |
        export PATH=/opt/nodejs/node-v16.13.0-linux-x64/bin:$PATH
        ./node_modules/.bin/wait-on http://localhost:3000
        ./node_modules/.bin/cypress run --record --key ${cypress_record_key} --reporter junit

  copy-cmdrc:
    command: shell.exec
    params:
      working_dir: spruce
      script: |
        cp env/.cmdrc_sample.json env/.cmdrc.json

  attach-results:
    command: attach.xunit_results
    params:
      files:
        - "./spruce/bin/cypress/*.xml"
        - "./spruce/bin/jest/*.xml"

  attach-cypress-screenshots:
    command: s3.put
    type: system
    params:
      aws_key: ${aws_key}
      aws_secret: ${aws_secret}
      local_files_include_filter:
        ["spruce/cypress/screenshots/*"]
      remote_file: spruce/${task_id}/
      bucket: mciuploads
      content_type: image/png
      permissions: public-read
      display_name: "screenshot:"

  attach-cypress-videos:
    command: s3.put
    type: system
    params:
      aws_key: ${aws_key}
      aws_secret: ${aws_secret}
      local_files_include_filter:
        ["spruce/cypress/videos/*"]
      remote_file: spruce/${task_id}/
      bucket: mciuploads
      content_type: video/mp4
      permissions: public-read
      display_name: "video:"

  attach-server-logs:
    command: s3.put
    type: system
    params:
      aws_key: ${aws_key}
      aws_secret: ${aws_secret}
      local_files_include_filter:
        ["evergreen/server_logs.txt"]
      remote_file: spruce/${task_id}/
      bucket: mciuploads
      content_type: text/plain
      permissions: public-read
      display_name: "server logs"

  attach-source-map:
    command: s3.put
    type: system
    params:
      aws_key: ${aws_key}
      aws_secret: ${aws_secret}
      local_file: "spruce/build/source_map.html"
      remote_file: spruce/${task_id}/source_map.html
      bucket: mciuploads
      content_type: text/html
      permissions: public-read
      display_name: "source map"

  attach-storybook:
    command: s3.put
    type: system
    params:
      aws_key: ${aws_key}
      aws_secret: ${aws_secret}
      local_files_include_filter:
        - storybook-static/
      remote_file: spruce/${task_id}/storybook/
      bucket: mciuploads
      content_type: text/html
      permissions: public-read
      display_name: storybook-
    
  setup-credentials:
    command: shell.exec
    params:
      working_dir: spruce
      script: |
        echo "Generating .cmdrc.json"
        REACT_APP_BUGSNAG_API_KEY=${REACT_APP_BUGSNAG_API_KEY} REACT_APP_NEW_RELIC_ACCOUNT_ID=${REACT_APP_NEW_RELIC_ACCOUNT_ID} REACT_APP_NEW_RELIC_AGENT_ID=${REACT_APP_NEW_RELIC_AGENT_ID} REACT_APP_NEW_RELIC_APPLICATION_ID=${REACT_APP_NEW_RELIC_APPLICATION_ID} REACT_APP_NEW_RELIC_LICENSE_KEY=${REACT_APP_NEW_RELIC_LICENSE_KEY} REACT_APP_NEW_RELIC_TRUST_KEY=${REACT_APP_NEW_RELIC_TRUST_KEY} REACT_APP_DEPLOYS_EMAIL=${REACT_APP_DEPLOYS_EMAIL} node cli-scripts/setup-credentials.js

        echo "populating evergreen.yml"
        cat <<EOF > .evergreen.yml
        api_server_host: ${evergreen_api_server_host}
        ui_server_host: ${evergreen_ui_server_host}
        api_key: ${evergreen_api_key}
        user: ${evergreen_user}
        EOF

        echo "Done populating"

  deploy-to-prod:
    command: shell.exec
    params:
      working_dir: spruce
      script: |
        export PATH=/opt/nodejs/node-v16.13.0-linux-x64/bin:$PATH
        BUCKET=${bucket} AWS_ACCESS_KEY_ID=${aws_key} AWS_SECRET_ACCESS_KEY=${aws_secret}  yarn deploy; yarn upload-source-maps;

  build-prod:
    command: shell.exec
    params:
      working_dir: spruce
      script: |
        export PATH=/opt/nodejs/node-v16.13.0-linux-x64/bin:$PATH
        chmod +x appVersion.sh
        . ./appVersion.sh
        echo "Building Production version: $REACT_APP_VERSION"
        yarn build:prod
  
  send-email:
    command: shell.exec
    params:
      working_dir: spruce
      script: |
        export AUTHOR_EMAIL=${author_email}
        export REACT_APP_DEPLOYS_EMAIL=${REACT_APP_DEPLOYS_EMAIL}
        bash email.sh


#######################################
#                Tasks                #
#######################################

tasks:
  - name: compile
    commands:
    - func: get-project
    - func: yarn-install
    - func: copy-cmdrc
    - func: sym-link
    - func: yarn-build
    - func: yarn-analyze

  - name: storybook
    commands:
    - func: get-project
    - func: yarn-install
    - func: yarn-build-storybook
    - func: attach-storybook

  - name: test
    commands:
    - func: get-project
    - func: yarn-install
    - func: yarn-test

  - name: lint
    commands:
    - func: get-project
    - func: sym-link
    - func: yarn-install
    - func: yarn-eslint

  - name: type_check
    commands:
    - func: get-project
    - func: sym-link
    - func: yarn-install
    - func: yarn-tsc

  - name: snapshots
    commands:
    - func: get-project
    - func: yarn-install
    - func: yarn-snapshot

  - name: e2e_test
    commands:
    - func: get-evergreen-project
    - func: setup-mongodb
    - func: copy-cmdrc
    - func: run-make-background
      vars:
        target: local-evergreen
    - func: yarn-install
    - func: sym-link
    - func: yarn-start
    - func: run-cypress-tests
    
  - name: send_email
    commands:
    - func: get-project
    - func: setup-credentials
    - func: send-email

  - name: check_codegen
    commands:
    - func: get-project
    - func: sym-link
    - func: yarn-install
    - func: check-codegen

  - name: deploy_to_prod
    commands:
    - func: get-project
    - func: setup-credentials
    - func: yarn-install
    - func: sym-link
    - func: build-prod
    - func: deploy-to-prod
    - func: send-email


buildvariants:
  - name: ubuntu1604
    display_name: Ubuntu 16.04
    run_on:
    - ubuntu1604-test
    modules:
      - evergreen
    tasks:
    - name: compile
    - name: test
    - name: lint
    - name: type_check
    - name: e2e_test
    - name: storybook
    - name: check_codegen
    - name: snapshots
    - name: deploy_to_prod
      git_tag_only: true
      patchable: false
      priority: 100

post:
  - func: attach-results
  - func: attach-cypress-screenshots
  - func: attach-cypress-videos
  - func: attach-server-logs
  - func: attach-source-map
