stepback: true
command_type: test
ignore:
  - "*.md"
  - ".github/*"

functions:
  get-project:
    command: git.get_project
    type: setup
    params:
      directory: spruce

  npm-install:
    command: subprocess.exec
    type: setup
    params:
      working_dir: spruce
      binary: npm
      args: [install]

  npm-test:
    command: subprocess.exec
    params:
      working_dir: spruce
      binary: npm
      args: [test, --, -u, --reporters=default, --reporters=jest-junit]
      env:
        CI: "true"

  npm-lint:
    command: subprocess.exec
    params:
      working_dir: spruce
      binary: npm
      args: [run, lint]

  npm-build:
    command: subprocess.exec
    params:
      working_dir: spruce
      binary: npm
      args: [run, build]

  npm-build:
    command: subprocess.exec
    params:
      working_dir: spruce
      binary: npm
      args: [run, build]

  npm-coverage:
    command: subprocess.exec
    params:
      working_dir: spruce
      binary: npm
      args: [run, coverage]

  attach-results:
    command: attach.xunit_results
    params:
      files:
        - "./spruce/junit.xml"

tasks:
  - name: compile
    commands:
    - func: get-project
    - func: npm-install
    - func: npm-build
    - func: npm-build
  - name: test
    commands:
    - func: get-project
    - func: npm-install
    - func: npm-test
    - func: attach-results
  - name: lint
    commands:
    - func: get-project
    - func: npm-install
    - func: npm-lint
  - name: coverage
    commands:
    - func: get-project
    - func: npm-install
    - func: npm-coverage

buildvariants:
  - name: ubuntu1804
    display_name: Ubuntu 18.04
    run_on:
    - ubuntu1804-test
    tasks:
    - name: compile
    - name: test
    - name: lint
    - name: coverage
