import {
  BannerTheme,
  ProjectHealthView,
  ProjectSettingsQuery,
  RepoSettingsQuery,
  MergeQueue,
} from "gql/generated/types";

const projectBase: ProjectSettingsQuery["projectSettings"] = {
  aliases: [
    {
      alias: "__github",
      description: "",
      gitTag: "",
      id: "1",
      remotePath: "",
      task: ".*",
      taskTags: [],
      variant: ".*",
      variantTags: [],
    },
    {
      alias: "__commit_queue",
      description: "",
      gitTag: "",
      id: "3",
      remotePath: "",
      task: "^lint$",
      taskTags: [],
      variant: "^ubuntu1604$",
      variantTags: [],
    },
    {
      alias: "__git_tag",
      description: "",
      gitTag: "tagName",
      id: "5",
      remotePath: "./evergreen.yml",
      task: "",
      taskTags: [],
      variant: "",
      variantTags: [],
    },
  ],
  githubWebhooksEnabled: true,
  projectRef: {
    admins: [],
    banner: {
      text: "",
      theme: BannerTheme.Announcement,
    },
    batchTime: 0,
    branch: null,
    buildBaronSettings: {
      ticketCreateProject: null,
      ticketSearchProjects: [],
    },
    commitQueue: {
      enabled: null,
      mergeMethod: "",
      mergeQueue: MergeQueue.Evergreen,
      message: "",
    },
    containerSizeDefinitions: [
      {
        cpu: 1024,
        memoryMb: 1024,
        name: "default",
      },
    ],
    deactivatePrevious: null,
    disabledStatsCache: null,
    dispatchingDisabled: null,
    displayName: null,
    enabled: false,
    externalLinks: [
      {
        displayName: "a link display name",
        requesters: ["gitter_request", "patch_request"],
        urlTemplate: "https:/a-link-template-{version_id}.com",
      },
    ],
    gitTagAuthorizedTeams: [],
    gitTagAuthorizedUsers: ["privileged"],
    gitTagVersionsEnabled: null,
    githubChecksEnabled: null,
    githubTriggerAliases: null,
    id: "project",
    identifier: "project",
    manualPrTestingEnabled: null,
    notifyOnBuildFailure: null,
    owner: "evergreen-ci",
    parsleyFilters: [
      {
        caseSensitive: true,
        exactMatch: true,
        expression: "filter_1",
      },
      {
        caseSensitive: false,
        exactMatch: false,
        expression: "filter_2",
      },
    ],
    patchTriggerAliases: null,
    patchingDisabled: null,
    perfEnabled: true,
    periodicBuilds: [],
    prTestingEnabled: null,
    projectHealthView: ProjectHealthView.Failed,
    remotePath: null,
    repo: "evergreen",
    repoRefId: "repo",
    repotrackerDisabled: null,
    restricted: true,
    spawnHostScriptPath: null,
    stepbackDisabled: null,
    taskAnnotationSettings: {
      fileTicketWebhook: {
        endpoint: null,
        secret: null,
      },
      jiraCustomFields: [],
    },
    taskSync: {
      configEnabled: null,
      patchEnabled: null,
    },
    triggers: [],
    versionControlEnabled: true,
    workstationConfig: {
      gitClone: null,
      setupCommands: [
        {
          command: 'echo "hello spruce"',
          directory: "sophie.stadler",
        },
      ],
    },
  },
  vars: {
    adminOnlyVars: ["test_name"],
    privateVars: ["test_name"],
    vars: { test_name: "", test_two: "val" },
  },
};

const repoBase: RepoSettingsQuery["repoSettings"] = {
  aliases: [
    {
      alias: "__github_checks",
      description: "",
      gitTag: "",
      id: "2",
      remotePath: "",
      task: "",
      taskTags: ["tTag"],
      variant: "",
      variantTags: ["vTag"],
    },
    {
      alias: "my alias name",
      description: "my description",
      gitTag: "",
      id: "4",
      remotePath: "",
      task: "",
      taskTags: ["hi"],
      variant: "",
      variantTags: ["okay"],
    },
  ],
  githubWebhooksEnabled: true,
  projectRef: {
    admins: ["admin"],
    batchTime: 12,
    buildBaronSettings: {
      ticketCreateProject: "EVG",
      ticketSearchProjects: ["EVG"],
    },
    commitQueue: {
      enabled: true,
      mergeMethod: "squash",
      mergeQueue: MergeQueue.Github,
      message: "Commit Queue Message",
    },
    deactivatePrevious: true,
    disabledStatsCache: false,
    dispatchingDisabled: true,
    displayName: "",
    externalLinks: [
      {
        displayName: "a link display name",
        requesters: ["gitter_request", "patch_request"],
        urlTemplate: "https:/a-link-template-{version_id}.com",
      },
    ],
    gitTagAuthorizedTeams: [],
    gitTagAuthorizedUsers: ["admin"],
    gitTagVersionsEnabled: false,
    githubChecksEnabled: true,
    githubTriggerAliases: ["alias1"],
    id: "123",
    manualPrTestingEnabled: false,
    notifyOnBuildFailure: false,
    owner: "evergreen-ci",
    patchTriggerAliases: [
      {
        alias: "alias1",
        childProjectIdentifier: "spruce",
        parentAsModule: "",
        status: "succeeded",
        taskSpecifiers: [
          {
            patchAlias: "alias2",
            taskRegex: "",
            variantRegex: "",
          },
          {
            patchAlias: "",
            taskRegex: ".*",
            variantRegex: ".*",
          },
        ],
      },
    ],
    patchingDisabled: false,
    perfEnabled: true,
    periodicBuilds: [
      {
        alias: "",
        configFile: "evergreen.yml",
        cron: "",
        id: "123",
        intervalHours: 24,
        message: "",
        nextRunTime: new Date("2022-03-30T17:07:10.942Z"),
      },
      {
        alias: "test",
        configFile: "evergreen.yml",
        cron: "*/5 * * * *",
        id: "456",
        intervalHours: 0,
        message: "Build Message",
        nextRunTime: new Date("2022-03-30T17:07:10.942Z"),
      },
    ],
    prTestingEnabled: false,
    remotePath: "evergreen.yml",
    repo: "spruce",
    repotrackerDisabled: false,
    restricted: true,
    spawnHostScriptPath: "/test/path",
    stepbackDisabled: true,
    taskAnnotationSettings: {
      fileTicketWebhook: {
        endpoint: "endpoint",
        secret: "secret",
      },
      jiraCustomFields: [
        {
          displayText: "Custom Field",
          field: "customField",
        },
      ],
    },
    taskSync: {
      configEnabled: true,
      patchEnabled: true,
    },
    triggers: [
      {
        alias: "my-alias",
        buildVariantRegex: ".*",
        configFile: ".evergreen.yml",
        dateCutoff: 1,
        level: "task",
        project: "spruce",
        status: "succeeded",
        taskRegex: ".*",
      },
    ],
    versionControlEnabled: false,
    workstationConfig: {
      gitClone: true,
      setupCommands: [],
    },
  },
  vars: {
    adminOnlyVars: [],
    privateVars: [],
    vars: { repo_name: "repo_value" },
  },
};

export const data = {
  projectBase,
  repoBase,
};
